"""Synthetic, deterministic tests for the MARKER-DRIVEN calibration path.

Everything here is generated by `make_face_frame` -- no video file from the rig, no randomness
that matters (the only RNG is a seeded +-1 grey-level dither, needed so a synthetic "dwell" has a
non-zero frame-to-frame metric like a real sensor does).

The synthetic frame reproduces the parts of the real rig that the marker calibration path
actually depends on (see `calibration`'s module docstring and `marker_band`'s):

  * two glowing TUBE ROW-BANDS, one above and one below the marker band, each spanning 8 vial
    columns -- these carry the y extents of the 16 slots;
  * the central MARKER BAND: two thin bright strips carrying one opaque sticker per vial column,
    alternating upper/lower, which is what encodes both the vial x boundaries and the face id;
  * a large SATURATED STAGE along the bottom edge that is BRIGHTER than either tube row and tall
    enough to qualify as a row-band candidate. On the real rig this is the illuminated stage
    (measured rows ~893-1023 at mean ~228, versus the lower tube row at ~127), so any
    "brightest/biggest run wins" rule picks it instead of a tube row. Keeping it here pins the
    rule that actually works: pick the run NEAREST THE MARKER BAND on each side.

Face "A" is the pattern as built; face "B" is the same pattern with the two strips swapped, which
is what a 180 degree drum flip produces.
"""
from __future__ import annotations

import json
import os

import cv2
import numpy as np
import pytest

from flygym_tracker.calibration import (
    Dwell,
    MarkerCalibParams,
    build_calibration_from_markers,
    build_two_face_calibration,
    detect_calibration,
    find_dwells,
    load_calibration,
    marker_detector_from_calibration,
    register_faces_from_dwells,
    save_calibration,
    suspicious_vials,
    tube_row_bands,
)
from flygym_tracker.marker_band import MarkerBandDetector
from flygym_tracker.types import Calibration, FaceCalibration, VialROI

# --- synthetic rig geometry (proportioned like the real 1280x1024 frame, scaled down) ---------
H, W = 760, 800
BG = 20                       # unlit surround
HARDWARE = 12                 # dark mounting hardware around/behind the marker strips
UPPER_BAND = (60, 292)        # HALF-OPEN rows of the upper tube row
LOWER_BAND = (410, 642)       # HALF-OPEN rows of the lower tube row
STRIP_UPPER = (320, 340)      # INCLUSIVE rows of the upper marker strip
STRIP_LOWER = (360, 380)      # INCLUSIVE rows of the lower marker strip
STAGE_ROW = 670               # saturated stage occupies [STAGE_ROW, H): brighter than the tubes
TUBE_CORE = 150               # bright tube body
TUBE_EDGE = 85                # dimmer rows at each band's outer edge (the tube mouths)
EDGE_ROWS = 24
TUBE_DIM = 45                 # a slot whose column barely lights: SUSPICIOUS, never auto-excluded
STRIP_LIT = 250
STAGE_VAL = 255

N_VIALS = 8
VIAL_X0 = 80
VIAL_PITCH = 80
#: ground-truth INCLUSIVE (x0, x1) of every vial column -- what `vial_boundaries` must return.
TRUE_SPANS = [(VIAL_X0 + i * VIAL_PITCH, VIAL_X0 + (i + 1) * VIAL_PITCH - 1) for i in range(N_VIALS)]
X_EXTENT = (TRUE_SPANS[0][0], TRUE_SPANS[-1][1])
#: the region between the two tube rows -- marker strips + hardware -- excluded from the mask.
TRUE_CENTRAL = (UPPER_BAND[1], LOWER_BAND[0])


def make_face_frame(swap: bool = False, dim_columns=(), dither: int = 0) -> np.ndarray:
    """Build a synthetic drum-face frame.

    Args:
        swap: emit the 180-degree-flipped face (upper/lower strip contents exchanged).
        dim_columns: 0-based vial columns whose tube barely lights, in BOTH rows. These are the
            real rig's dim end columns (DESIGN.md §2) -- the ones the brightness-based detector
            wrongly called empty.
        dither: peak amplitude of a seeded +-`dither` grey-level dither, so consecutive frames of
            a synthetic "dwell" differ slightly, as a real sensor's do.
    """
    img = np.full((H, W), BG, dtype=np.uint8)
    img[STAGE_ROW:, :] = STAGE_VAL
    img[TRUE_CENTRAL[0]:TRUE_CENTRAL[1], :] = HARDWARE

    x0, x1 = X_EXTENT
    for y0, y1 in (UPPER_BAND, LOWER_BAND):
        img[y0:y1, x0:x1 + 1] = TUBE_EDGE
        img[y0 + EDGE_ROWS:y1 - EDGE_ROWS, x0:x1 + 1] = TUBE_CORE
        for c in dim_columns:
            sx0, sx1 = TRUE_SPANS[c]
            img[y0:y1, sx0:sx1 + 1] = TUBE_DIM

    # Marker band: one opaque sticker per column, alternating upper/lower. The lit run for
    # column i therefore falls on the OPPOSITE strip; `swap` exchanges the two.
    for i, (sx0, sx1) in enumerate(TRUE_SPANS):
        lit_upper = (i % 2 == 1) != swap
        lit_lower = (i % 2 == 0) != swap
        for (r0, r1), lit in ((STRIP_UPPER, lit_upper), (STRIP_LOWER, lit_lower)):
            if lit:
                img[r0:r1 + 1, sx0:sx1 + 1] = STRIP_LIT

    if dither:
        rng = np.random.default_rng(0)
        noise = rng.integers(-dither, dither + 1, size=img.shape, endpoint=False)
        img = np.clip(img.astype(np.int16) + noise, 0, 255).astype(np.uint8)
    return img


class StubDetector:
    """Minimal duck-typed stand-in for `MarkerBandDetector`.

    `build_calibration_from_markers` consumes exactly two methods; this pins that contract and
    lets a test feed the builder x-spans of its own choosing, independent of any CV.
    """

    def __init__(self, spans=None, strips=None):
        self.spans = list(spans if spans is not None else TRUE_SPANS)
        self.strips = list(strips if strips is not None else [STRIP_UPPER, STRIP_LOWER])

    def find_strips(self, frame_gray):
        return list(self.strips)

    def vial_boundaries(self, frame_gray):
        return list(self.spans)


@pytest.fixture
def detector() -> MarkerBandDetector:
    """A real detector with both synthetic faces registered."""
    det = MarkerBandDetector()
    det.register_face(make_face_frame(swap=False), "A")
    det.register_face(make_face_frame(swap=True), "B")
    return det


# =============================================================================================
# The synthetic frame is a faithful stand-in: the REAL detector reads it correctly
# =============================================================================================
def test_real_detector_reads_the_synthetic_band():
    det = MarkerBandDetector()
    frame = make_face_frame()
    assert det.find_strips(frame) == [STRIP_UPPER, STRIP_LOWER]
    assert det.vial_boundaries(frame) == TRUE_SPANS


def test_real_detector_separates_the_two_synthetic_faces(detector):
    assert detector.identify_face(make_face_frame(swap=False)) == "A"
    assert detector.identify_face(make_face_frame(swap=True)) == "B"


# =============================================================================================
# Tube row bands: found from the frame, and NOT confused by the brighter stage
# =============================================================================================
#: The row-mean profile is smoothed over `MarkerCalibParams.band_smooth` (9) rows before it is
#: thresholded, which pulls each run's edges in by about half a window. Band edges are therefore
#: compared with this tolerance rather than exactly.
BAND_TOL = 6


def assert_band_close(got, expected, tol=BAND_TOL):
    assert abs(got[0] - expected[0]) <= tol and abs(got[1] - expected[1]) <= tol, \
        f"band {got} not within {tol}px of {expected}"


def test_tube_row_bands_are_the_runs_adjacent_to_the_marker_band():
    gray = make_face_frame()
    upper, lower, central = tube_row_bands(gray, [STRIP_UPPER, STRIP_LOWER], X_EXTENT)

    assert_band_close(upper, UPPER_BAND)
    assert_band_close(lower, LOWER_BAND)
    assert central == (upper[1], lower[0])
    # the whole marker band lies inside the excluded central region, and neither tube row
    # touches it
    assert central[0] <= STRIP_UPPER[0] and STRIP_LOWER[1] < central[1]
    assert upper[1] <= STRIP_UPPER[0] and lower[0] > STRIP_LOWER[1]
    # each band still covers the bright tube core it was meant to find
    assert upper[0] <= UPPER_BAND[0] + EDGE_ROWS and upper[1] >= UPPER_BAND[1] - EDGE_ROWS
    assert lower[0] <= LOWER_BAND[0] + EDGE_ROWS and lower[1] >= LOWER_BAND[1] - EDGE_ROWS


def test_tube_row_bands_reject_the_brighter_stage():
    """The stage is brighter (255 vs 150) and tall enough to be a candidate run -- the lower
    tube row must still win, because it is the run NEAREST the band."""
    gray = make_face_frame()
    _, lower, _ = tube_row_bands(gray, [STRIP_UPPER, STRIP_LOWER], X_EXTENT)
    assert_band_close(lower, LOWER_BAND)
    assert lower[1] <= STAGE_ROW, "picked the saturated stage instead of the tube row"
    assert float(gray[STAGE_ROW:].mean()) > float(gray[lower[0]:lower[1]].mean())


def test_tube_row_bands_raise_when_a_side_is_missing():
    """With nothing lit below the marker band at all, there is no lower row to find."""
    gray = make_face_frame()
    gray[LOWER_BAND[0]:, :] = BG            # blank the lower tube row AND the stage
    with pytest.raises(ValueError, match="tube row on each side"):
        tube_row_bands(gray, [STRIP_UPPER, STRIP_LOWER], X_EXTENT)


# =============================================================================================
# build_calibration_from_markers -- geometry
# =============================================================================================
@pytest.mark.parametrize("use_stub", [True, False])
def test_16_rois_row_major_ids(use_stub):
    gray = make_face_frame()
    det = StubDetector() if use_stub else MarkerBandDetector()
    face_cal, mask, overlay = build_calibration_from_markers(gray, "A", det)

    assert isinstance(face_cal, FaceCalibration)
    assert face_cal.name == "A"
    vials = face_cal.vials
    assert len(vials) == 16
    assert [v.id for v in vials] == list(range(1, 17))
    assert [v.row for v in vials] == [0] * 8 + [1] * 8     # upper row 1..8, lower row 9..16
    assert [v.col for v in vials] == list(range(8)) * 2

    assert mask.dtype == np.uint8 and mask.shape == (H, W)
    assert overlay.shape == (H, W, 3)


@pytest.mark.parametrize("use_stub", [True, False])
def test_x_spans_come_from_the_marker_boundaries(use_stub):
    """The whole point of this path: vial x positions are the marker's, exactly, not a guess."""
    gray = make_face_frame()
    det = StubDetector() if use_stub else MarkerBandDetector()
    face_cal, _, _ = build_calibration_from_markers(gray, "A", det)

    for row_offset in (0, 8):
        for col, (sx0, sx1) in enumerate(TRUE_SPANS):
            v = face_cal.vials[row_offset + col]
            assert (v.x, v.x + v.w - 1) == (sx0, sx1), f"vial {v.id} x-span"


def test_x_spans_follow_a_stub_detectors_own_boundaries():
    """Feed deliberately off-grid spans: the builder must use them verbatim, not re-derive."""
    odd = [(60 + i * 90, 60 + i * 90 + 71) for i in range(8)]
    face_cal, _, _ = build_calibration_from_markers(
        make_face_frame(), "A", StubDetector(spans=odd))
    assert [(v.x, v.x + v.w - 1) for v in face_cal.vials[:8]] == odd
    assert [(v.x, v.x + v.w - 1) for v in face_cal.vials[8:]] == odd


def test_upper_ids_sit_in_the_upper_band_and_lower_ids_below():
    face_cal, _, _ = build_calibration_from_markers(make_face_frame(), "A", StubDetector())
    for v in face_cal.vials[:8]:
        assert_band_close((v.y, v.y + v.h), UPPER_BAND)
    for v in face_cal.vials[8:]:
        assert_band_close((v.y, v.y + v.h), LOWER_BAND)
    # every box in a row shares one y extent ...
    assert len({(v.y, v.h) for v in face_cal.vials[:8]}) == 1
    assert len({(v.y, v.h) for v in face_cal.vials[8:]}) == 1
    # ... and the marker band lies strictly between the two rows, in neither of them
    top, bottom = face_cal.vials[0], face_cal.vials[8]
    assert top.y + top.h <= STRIP_UPPER[0]
    assert bottom.y > STRIP_LOWER[1]


# =============================================================================================
# build_calibration_from_markers -- illuminated mask
# =============================================================================================
def test_mask_excludes_the_central_band_and_the_stage():
    _, mask, _ = build_calibration_from_markers(make_face_frame(), "A", StubDetector())

    assert int(mask[TRUE_CENTRAL[0]:TRUE_CENTRAL[1]].max()) == 0, "central marker band leaked in"
    assert int(mask[STRIP_UPPER[0]:STRIP_LOWER[1] + 1].max()) == 0, "marker strips leaked in"
    assert int(mask[STAGE_ROW:].max()) == 0, "saturated stage leaked in"
    # ... while both tube rows keep trackable pixels
    assert int(mask[UPPER_BAND[0]:UPPER_BAND[1]].max()) == 255
    assert int(mask[LOWER_BAND[0]:LOWER_BAND[1]].max()) == 255
    assert set(np.unique(mask)).issubset({0, 255})


def test_mask_is_confined_to_the_vial_columns():
    _, mask, _ = build_calibration_from_markers(make_face_frame(), "A", StubDetector())
    x0, x1 = X_EXTENT
    assert int(mask[:, :x0].max()) == 0
    assert int(mask[:, x1 + 1:].max()) == 0


def test_every_vial_box_has_lit_pixels_when_the_face_is_evenly_lit():
    face_cal, mask, _ = build_calibration_from_markers(make_face_frame(), "A", StubDetector())
    for v in face_cal.vials:
        lit = int((mask[v.y:v.y + v.h, v.x:v.x + v.w] > 0).sum())
        assert lit > 0, f"vial {v.id} has no trackable pixels"


# =============================================================================================
# PRESENCE POLICY: never auto-exclude -- the bug this path exists to prevent
# =============================================================================================
def test_every_slot_defaults_to_present():
    face_cal, _, _ = build_calibration_from_markers(make_face_frame(), "A", StubDetector())
    assert all(v.present for v in face_cal.vials)
    assert [v.present for v in face_cal.vials] == [True] * 16


@pytest.mark.parametrize("dim", [(0,), (7,), (0, 7), (3,)])
def test_dark_slots_stay_present_and_are_flagged_instead(dim):
    """A slot whose column barely lights is REPORTED, never excluded.

    This is the regression guard for the real failure: the brightness-based detector marked a
    vial that was full of flies as absent, and `TrackerPipeline` then skipped it silently.
    """
    gray = make_face_frame(dim_columns=dim)
    face_cal, _, _ = build_calibration_from_markers(gray, "A", StubDetector())

    assert all(v.present for v in face_cal.vials), "a dark slot was auto-excluded"
    flagged = suspicious_vials(face_cal)
    expected = sorted([c + 1 for c in dim] + [c + 9 for c in dim])   # both rows of that column
    assert flagged == expected
    # the flag is advisory metadata only -- it must not have touched `present`
    assert [v.id for v in face_cal.vials if not v.present] == []


def test_evenly_lit_face_flags_nothing():
    face_cal, _, _ = build_calibration_from_markers(make_face_frame(), "A", StubDetector())
    assert suspicious_vials(face_cal) == []


def test_a_uniformly_dim_face_flags_nothing_rather_than_everything():
    """The suspicion cut is an AND of a relative and an absolute test, so a globally dim rig
    does not flag all 16 slots (which would tell a human nothing). Only what stands out
    RELATIVE to this face's own median is flagged."""
    gray = make_face_frame()
    x0, x1 = X_EXTENT
    for y0, y1 in (UPPER_BAND, LOWER_BAND):          # halve the lit core of EVERY slot
        mid = (y0 + y1) // 2
        gray[mid:y1 - EDGE_ROWS, x0:x1 + 1] = TUBE_EDGE

    face_cal, mask, _ = build_calibration_from_markers(gray, "A", StubDetector())
    lit = [q["lit_frac"] for q in face_cal.marker["vial_qc"]]
    assert max(lit) < 0.60, f"test setup: slots should all be under the absolute cut, got {lit}"
    assert suspicious_vials(face_cal) == [], "a uniformly dim face flagged slots as odd"
    assert all(v.present for v in face_cal.vials)


def test_a_dark_slot_is_still_flagged_on_a_dim_face():
    """... and the relative test still catches a genuine outlier on that same dim face."""
    gray = make_face_frame(dim_columns=(2,))
    x0, x1 = X_EXTENT
    for y0, y1 in (UPPER_BAND, LOWER_BAND):
        mid = (y0 + y1) // 2
        block = gray[mid:y1 - EDGE_ROWS, x0:x1 + 1]
        block[block == TUBE_CORE] = TUBE_EDGE

    face_cal, _, _ = build_calibration_from_markers(gray, "A", StubDetector())
    assert suspicious_vials(face_cal) == [3, 11]     # column 2 in both rows
    assert all(v.present for v in face_cal.vials)


def test_qc_records_lit_fraction_per_slot():
    gray = make_face_frame(dim_columns=(0,))
    face_cal, mask, _ = build_calibration_from_markers(gray, "A", StubDetector())
    qc = {q["id"]: q for q in face_cal.marker["vial_qc"]}
    assert len(qc) == 16
    assert qc[1]["lit_frac"] < qc[2]["lit_frac"], "the dim slot should have less lit area"
    assert qc[1]["suspicious"] is True and qc[2]["suspicious"] is False
    # lit_frac agrees with the mask it was measured from
    v2 = face_cal.vials[1]
    measured = float((mask[v2.y:v2.y + v2.h, v2.x:v2.x + v2.w] > 0).mean())
    assert abs(qc[2]["lit_frac"] - measured) < 0.01


def test_suspicious_vials_is_empty_for_a_non_marker_face():
    """`detect_calibration` bundles carry no marker metadata; the accessor must not blow up."""
    calib, _, _ = detect_calibration(make_face_frame(), face="A")
    assert suspicious_vials(calib.faces["A"]) == []


def test_marker_metadata_records_the_geometry_it_used():
    face_cal, _, _ = build_calibration_from_markers(make_face_frame(), "A", StubDetector())
    marker = face_cal.marker
    assert marker["source"] == "marker_band"
    assert marker["vial_spans"] == [list(s) for s in TRUE_SPANS]
    assert marker["strips"] == [list(STRIP_UPPER), list(STRIP_LOWER)]
    assert_band_close(marker["row_bands"]["upper"], UPPER_BAND)
    assert_band_close(marker["row_bands"]["lower"], LOWER_BAND)
    assert marker["central_band"] == [marker["row_bands"]["upper"][1],
                                      marker["row_bands"]["lower"][0]]
    assert marker["presence_policy"].startswith("all present")
    assert json.loads(json.dumps(marker)) == marker, "marker metadata must be JSON-safe"


def test_builder_rejects_a_detector_without_find_strips():
    class NoStrips:
        def vial_boundaries(self, frame):
            return TRUE_SPANS

    with pytest.raises(ValueError, match="find_strips"):
        build_calibration_from_markers(make_face_frame(), "A", NoStrips())


def test_builder_reports_a_missing_band():
    with pytest.raises(ValueError, match="marker band not visible"):
        build_calibration_from_markers(make_face_frame(), "A", StubDetector(strips=[]))


@pytest.mark.parametrize("n_spans", [7, 9])
def test_builder_rejects_a_span_count_that_is_not_eight(n_spans):
    """Anything but 8 columns would break the global-vial-id scheme SILENTLY.

    Ids here run 1..2*len(spans) while `pipeline.TrackerPipeline` computes global ids as
    `face_index*16 + local_id`. With 9 columns, face A's local id 17 and face B's local id 1
    both map to global id 17 -- two physical vials merged into one row of the output table,
    with nothing reporting it. So this must fail loudly at calibration time.
    """
    spans = [(60 + i * 70, 60 + i * 70 + 61) for i in range(n_spans)]
    with pytest.raises(ValueError, match="expected exactly 8"):
        build_calibration_from_markers(make_face_frame(), "A", StubDetector(spans=spans))


def test_box_w_frac_shrinks_boxes_about_the_span_centre():
    params = MarkerCalibParams(box_w_frac=0.5)
    face_cal, _, _ = build_calibration_from_markers(
        make_face_frame(), "A", StubDetector(), params=params)
    for v, (sx0, sx1) in zip(face_cal.vials[:8], TRUE_SPANS):
        assert v.w == (sx1 - sx0 + 1) // 2
        span_mid = (sx0 + sx1 + 1) / 2.0
        assert abs((v.x + v.w / 2.0) - span_mid) <= 1.0


# =============================================================================================
# Persistence round-trip (a two-face bundle)
# =============================================================================================
def _two_face_calibration():
    det = MarkerBandDetector()
    det.register_face(make_face_frame(swap=False), "A")
    det.register_face(make_face_frame(swap=True), "B")
    fa, ma, oa = build_calibration_from_markers(make_face_frame(swap=False), "A", det)
    fb, mb, ob = build_calibration_from_markers(make_face_frame(swap=True, dim_columns=(7,)), "B", det)
    calib = Calibration(image_width=W, image_height=H, faces={"A": fa, "B": fb}, notes="test")
    return calib, {"A": ma, "B": mb}, {"A": oa, "B": ob}


def test_save_load_roundtrip_two_faces(tmp_path):
    calib, masks, overlays = _two_face_calibration()
    out = str(tmp_path / "calib")
    save_calibration(calib, masks, out, overlay=overlays)

    for name in ("calibration.json", "illum_mask_A.png", "illum_mask_B.png",
                 "overlay_A.png", "overlay_B.png"):
        assert os.path.isfile(os.path.join(out, name)), name

    loaded = load_calibration(out)
    assert sorted(loaded.faces) == ["A", "B"]
    assert (loaded.image_width, loaded.image_height) == (W, H)
    for name in ("A", "B"):
        orig = calib.faces[name].vials
        got = loaded.faces[name].vials
        assert len(orig) == len(got) == 16
        for a, b in zip(orig, got):
            assert (a.id, a.row, a.col, a.x, a.y, a.w, a.h, a.present) == \
                   (b.id, b.row, b.col, b.x, b.y, b.w, b.h, b.present)
        assert all(v.present for v in got), "presence policy did not survive the round-trip"
        assert suspicious_vials(loaded.faces[name]) == suspicious_vials(calib.faces[name])

    # each face got its OWN mask, and both exclude the central band
    ma = cv2.imread(loaded.faces["A"].illum_mask_path, cv2.IMREAD_GRAYSCALE)
    mb = cv2.imread(loaded.faces["B"].illum_mask_path, cv2.IMREAD_GRAYSCALE)
    assert ma is not None and mb is not None
    assert int(ma[TRUE_CENTRAL[0]:TRUE_CENTRAL[1]].max()) == 0
    assert int(mb[TRUE_CENTRAL[0]:TRUE_CENTRAL[1]].max()) == 0
    assert not np.array_equal(ma, mb), "both faces were written the same mask"


def test_save_calibration_still_accepts_one_image_for_one_face(tmp_path):
    """Back-compat: the single-array form used by the auto/wizard paths is unchanged."""
    calib, _, _ = detect_calibration(make_face_frame(), face="A")
    _, mask, overlay = detect_calibration(make_face_frame(), face="A")
    out = str(tmp_path / "calib")
    save_calibration(calib, mask, out, overlay=overlay)
    assert os.path.isfile(os.path.join(out, "illum_mask_A.png"))
    assert os.path.isfile(os.path.join(out, "overlay_A.png"))
    assert np.array_equal(cv2.imread(os.path.join(out, "illum_mask_A.png"),
                                     cv2.IMREAD_GRAYSCALE), mask)


# =============================================================================================
# Two-face build from a video
# =============================================================================================
def write_flip_video(path: str, blocks=("A", "B", "A", "B"), dwell_frames: int = 20,
                     rotation_frames: int = 4) -> int:
    """Write a synthetic flip clip: dwell / rotation / dwell / ... Returns the frame count.

    Uncompressed AVI (fourcc 0) so the marker pattern survives byte-exact. Dwell frames carry a
    seeded +-1 dither so the frame-to-frame metric is non-zero as a real sensor's is; rotation
    frames are the face rolled sideways, which is a large global change exactly as a turning drum
    produces.
    """
    writer = cv2.VideoWriter(path, 0, 10.0, (W, H), False)
    assert writer.isOpened(), "could not open an uncompressed AVI writer"
    n = 0
    try:
        for b, face in enumerate(blocks):
            base = make_face_frame(swap=(face == "B"))
            rng = np.random.default_rng(100 + b)
            for _ in range(dwell_frames):
                dither = rng.integers(-1, 2, size=base.shape)
                writer.write(np.clip(base.astype(np.int16) + dither, 0, 255).astype(np.uint8))
                n += 1
            if b < len(blocks) - 1:
                for k in range(rotation_frames):
                    writer.write(np.roll(base, 90 * (k + 1), axis=1))
                    n += 1
    finally:
        writer.release()
    return n


def test_find_dwells_segments_the_flip_video(tmp_path):
    video = str(tmp_path / "flip.avi")
    write_flip_video(video)
    dwells, reps, size = find_dwells(video)

    assert size == (W, H)
    assert len(dwells) == 4, [(d.start, d.end) for d in dwells]
    assert all(d.length >= 15 for d in dwells)
    assert sorted(reps) == sorted(d.rep_index for d in dwells)
    # each representative frame sits inside its own dwell
    for d in dwells:
        assert d.start <= d.rep_index <= d.end


def test_register_faces_from_dwells_finds_two_faces(tmp_path):
    video = str(tmp_path / "flip.avi")
    write_flip_video(video)
    dwells, reps, _ = find_dwells(video)

    det = MarkerBandDetector()
    groups = register_faces_from_dwells(dwells, reps, det, MarkerCalibParams())

    assert sorted(groups) == ["A", "B"]
    assert sorted(det.templates) == ["A", "B"]
    assert [d.face for d in dwells] == ["A", "B", "A", "B"]
    # the two faces really are distinguished, with room to spare
    for d in dwells:
        assert d.face_score > 0.5, (d.face, d.face_score)


def test_register_faces_from_dwells_keeps_one_face_when_there_is_no_flip(tmp_path):
    video = str(tmp_path / "noflip.avi")
    write_flip_video(video, blocks=("A", "A", "A"))
    dwells, reps, _ = find_dwells(video)

    det = MarkerBandDetector()
    groups = register_faces_from_dwells(dwells, reps, det, MarkerCalibParams())
    assert sorted(groups) == ["A"]
    assert len(groups["A"]) == len(dwells)


def test_build_two_face_calibration_end_to_end(tmp_path):
    video = str(tmp_path / "flip.avi")
    write_flip_video(video)
    out = str(tmp_path / "calib_faces")

    det = MarkerBandDetector()
    calib = build_two_face_calibration(video, det, out)

    assert sorted(calib.faces) == ["A", "B"]
    assert (calib.image_width, calib.image_height) == (W, H)
    assert sum(len(fc.vials) for fc in calib.faces.values()) == 32
    for name in ("A", "B"):
        vials = calib.faces[name].vials
        assert [v.id for v in vials] == list(range(1, 17))
        assert all(v.present for v in vials)
        assert os.path.isfile(os.path.join(out, f"illum_mask_{name}.png"))
        assert os.path.isfile(os.path.join(out, f"overlay_{name}.png"))

    # the detector handed in is left ready to drive TrackerPipeline
    assert sorted(det.templates) == ["A", "B"]
    assert det.identify_face(make_face_frame(swap=False)) == "A"
    assert det.identify_face(make_face_frame(swap=True)) == "B"

    # ... and a detector rebuilt from the saved bundle alone behaves the same
    reloaded = marker_detector_from_calibration(load_calibration(out))
    assert reloaded is not None
    assert reloaded.identify_face(make_face_frame(swap=False)) == "A"
    assert reloaded.identify_face(make_face_frame(swap=True)) == "B"


def test_two_face_bundle_drives_global_vial_ids_1_to_32(tmp_path):
    """The 32-slot contract: face_index*16 + local_id, exactly as `TrackerPipeline` computes it."""
    video = str(tmp_path / "flip.avi")
    write_flip_video(video)
    out = str(tmp_path / "calib_faces")
    build_two_face_calibration(video, MarkerBandDetector(), out)

    calib = load_calibration(out)
    order = sorted(calib.faces)
    gvids = sorted(order.index(name) * 16 + v.id
                   for name, fc in calib.faces.items() for v in fc.vials)
    assert gvids == list(range(1, 33))


def test_build_two_face_calibration_rejects_a_missing_video(tmp_path):
    with pytest.raises(ValueError, match="could not open video"):
        build_two_face_calibration(str(tmp_path / "nope.avi"), MarkerBandDetector(),
                                   str(tmp_path / "out"))


# =============================================================================================
# CLI: calibrate-faces
# =============================================================================================
def test_cli_calibrate_faces(tmp_path, capsys):
    from flygym_tracker.cli import main

    video = str(tmp_path / "flip.avi")
    write_flip_video(video)
    out = str(tmp_path / "calib_faces")

    rc = main(["calibrate-faces", "--video", video, "--out", out])
    assert rc == 0
    printed = capsys.readouterr().out
    assert "faces found : A, B (2)" in printed
    assert "vials       : 32 total" in printed
    assert "global ids 1-16" in printed and "global ids 17-32" in printed
    assert "all present=True" in printed

    calib = load_calibration(out)
    assert sorted(calib.faces) == ["A", "B"]
    assert sum(len(fc.vials) for fc in calib.faces.values()) == 32


def test_cli_calibrate_faces_reports_suspicious_slots(tmp_path, capsys):
    """A dim column must show up in the summary a human reads -- not be silently dropped."""
    from flygym_tracker.cli import main

    video = str(tmp_path / "flip.avi")
    writer = cv2.VideoWriter(video, 0, 10.0, (W, H), False)
    assert writer.isOpened()
    try:
        for b, face in enumerate(("A", "B", "A", "B")):
            base = make_face_frame(swap=(face == "B"), dim_columns=(0,))
            rng = np.random.default_rng(200 + b)
            for _ in range(20):
                d = rng.integers(-1, 2, size=base.shape)
                writer.write(np.clip(base.astype(np.int16) + d, 0, 255).astype(np.uint8))
            if b < 3:
                for k in range(4):
                    writer.write(np.roll(base, 90 * (k + 1), axis=1))
    finally:
        writer.release()

    rc = main(["calibrate-faces", "--video", str(video), "--out", str(tmp_path / "c")])
    assert rc == 0
    printed = capsys.readouterr().out
    assert "SUSPICIOUS" in printed
    assert "[1, 9]" in printed          # column 0 in both rows
    assert "still measured" in printed


def test_cli_calibrate_faces_missing_video_is_a_message_not_a_traceback(tmp_path, capsys):
    from flygym_tracker.cli import main

    rc = main(["calibrate-faces", "--video", str(tmp_path / "nope.avi"),
               "--out", str(tmp_path / "out")])
    assert rc == 2
    assert "could not open video" in capsys.readouterr().err


def test_cli_calibrate_faces_rejects_unknown_marker_params(tmp_path, capsys):
    import yaml

    from flygym_tracker.cli import main

    cfg = tmp_path / "cfg.yaml"
    cfg.write_text(yaml.safe_dump({"calibration": {"marker_params": {"not_a_knob": 1}}}),
                   encoding="utf-8")
    video = str(tmp_path / "flip.avi")
    write_flip_video(video, blocks=("A", "B"))

    rc = main(["calibrate-faces", "--video", video, "--out", str(tmp_path / "o"),
               "--config", str(cfg)])
    assert rc == 1
    assert "unknown calibration.marker_params key(s): not_a_knob" in capsys.readouterr().err


def test_cli_calibrate_faces_accepts_marker_params_from_config(tmp_path):
    import yaml

    from flygym_tracker.cli import main

    cfg = tmp_path / "cfg.yaml"
    cfg.write_text(yaml.safe_dump({"calibration": {"marker_params": {"box_w_frac": 0.5}}}),
                   encoding="utf-8")
    video = str(tmp_path / "flip.avi")
    write_flip_video(video, blocks=("A", "B"))
    out = str(tmp_path / "o")

    assert main(["calibrate-faces", "--video", video, "--out", out, "--config", str(cfg)]) == 0
    calib = load_calibration(out)
    for v, (sx0, sx1) in zip(calib.faces["A"].vials[:8], TRUE_SPANS):
        assert v.w == (sx1 - sx0 + 1) // 2


# =============================================================================================
# Real rig data (skipped when the clip is not on this machine)
# =============================================================================================
REAL_VIDEO = os.path.join(os.path.dirname(__file__), "..", "..",
                          "Bonsai related devs", "Good Markers.avi")


@pytest.mark.skipif(not os.path.isfile(REAL_VIDEO), reason="real flip video not available")
def test_real_video_yields_two_faces_of_16(tmp_path):
    out = str(tmp_path / "calib_faces")
    calib = build_two_face_calibration(REAL_VIDEO, MarkerBandDetector(), out)

    assert sorted(calib.faces) == ["A", "B"]
    assert (calib.image_width, calib.image_height) == (1280, 1024)
    for name in ("A", "B"):
        fc = calib.faces[name]
        assert len(fc.vials) == 16
        assert all(v.present for v in fc.vials), "the real rig must not auto-exclude any slot"
        assert [v.id for v in fc.vials] == list(range(1, 17))
        assert len(fc.marker["vial_spans"]) == 8
        # the upper row sits above the marker band and the lower row below it
        strips = fc.marker["strips"]
        assert fc.vials[0].y + fc.vials[0].h <= min(s[0] for s in strips)
        assert fc.vials[8].y >= max(s[1] for s in strips)
        mask = cv2.imread(os.path.join(out, f"illum_mask_{name}.png"), cv2.IMREAD_GRAYSCALE)
        cb = fc.marker["central_band"]
        assert int(mask[cb[0]:cb[1]].max()) == 0
        assert int((mask > 0).sum()) > 100_000
